### ISSUE TITLE
Loading SC3 in R 3.4.1 

### ISSUE THREAD

**Issue by harrydgnt** [hemberg-lab/SC3#42]
Hello 

I used SC3 previously and I recently update R from 3.3 to 3.4 and I am having problem with loading SC3. 

When I try to load SC3 after scater, i get following error:

`> library(scater)
> library(SC3)
Error: package or namespace load failed for ‘SC3’:
 object ‘fData<-’ is not exported by 'namespace:scater`

Any idea how to fix this?

Thank you 

Harry

**Comment by wikiselev** [comment]
Hi, thanks for your message! Could you please send me your `sessionInfo()`?
Cheers,
Vlad

P.S. From the error it looks like you have a development version of `scater` installed. In the newest version they have moved from `SCESet` class to `SingleCellExperiment` class and I haven't modified `SC3` to deal with this yet. If you reinstall your `scater` from Bioconductor release branch you should be ok. Otherwise, I will update `SC3` before the next release of Bioconductor (October 31) and it will work with the new `SingleCellExperiment` class. Hope this helps.

**Comment by wikiselev** [comment]
No response in a month, so I am closing it.
