### ISSUE TITLE
Excluding principal components from clustering

### ISSUE THREAD

**Issue by martabrozynska** [hemberg-lab/SC3#71]
Hi,
Would it be possible to exclude a specific principal component (PC) from the clustering using SC3? What I'd like to do is to run the clustering on PCs without the PC1 (it explains a variation I'm not interested in).
Hope it makes sense.
Thanks!

**Comment by CodeInTheSkies** [comment]
Hi @martabrozynska ,  I'm not attempting to answer your question but rather it looks like you can answer one of my questions that I posted earlier here: https://github.com/hemberg-lab/SC3/issues/75

Basically, I would like to know if one can run SC3 clustering on PCs rather than the expression matrix.  It looks like you have done this, correct?

If so, could you please let me know what's the correct way to do this?  I mean the steps, at what point can one bring in the PC data (from Seurat, for e.g.), etc.  

Thanks in advance for your response.

**Comment by wikiselev** [comment]
Hi, sorry for a long delay. I think the answer to the original question is `no`, in the current implementation the first `n` principal components are used for clustering and there is no parameter controlling your preferred behaviour. However, you can manually remove components from the `metadata(sce)$sc3$transformations` matrices. See more details [here](https://bioconductor.org/packages/release/bioc/vignettes/SC3/inst/doc/SC3.html#sc3_calc_transfs).
